version: '3.7'

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        working_dir: /usr/local/site/
        volumes:
        - ./backend/:/usr/local/site/
        ports:
        - 8000:8000
        env_file:
        - ./.env.dev
    frontend:
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        depends_on:
            - backend
        volumes:
        - ./nginx/build/:/usr/local/build/
        - ./backend/carebackend/django-static/:/usr/local/django-static/
        - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
        - ./nginx/nginx_auth:/etc/nginx/nginx_auth